Since Port is seperated for MARIADB variables, it needs to be joined …
YOURLS/charts pull request #407
Opened 2024-11-29 22:31 UTC by halkeye

…for YOURLS_DB_HOST

2024-11-30 21:56 UTC, LeoColomb requested changes
Thanks for submitting this pull request, @halkeye.
Sounds good to me.
Please see my inline comment.
Also, the chart version needs to be bumped.

2024-11-30 21:56 UTC, LeoColomb commented on charts/yourls/templates/deployment.yaml
> +              value: "{{ include "yourls.databaseHost" . }}:{{ include "yourls.databasePort" . }}"
Let's use proper string interpolation:
```suggestion
              value: {{ printf "%s:%s" (include "yourls.databaseHost" .) (include "yourls.databasePort" .) }}
```

2024-12-04 11:45 UTC, LeoColomb approved these changes

2024-12-04 11:59 UTC, merged

2024-12-05 00:47 UTC, halkeye commented
Thanks for following up and doing it. I got very distracted this week.